#ifndef __COMPONENTENUM_H
#define __COMPONENTENUM_H

enum {
 IUSMALLCOMPONENT        ,//0
 USTBIGCOMPONENT         ,//1
 ACMDSMALLCOMPONENT      ,//2
 DOUTBIGCOMPONENT        ,//3
 DOUTSMALLCOMPONENT      ,//4
 DTRBIGCOMPONENT         ,//5
 ANDBIGCOMPONENT         ,//6
 UPRBIGCOMPONENT         ,//7
 DVBIGCOMPONENT          ,//8
 DVSMALLCOMPONENT        ,//9
 GCMDSMALLCOMPONENT      ,//10
 KEYBIGCOMPONENT         ,//11
 MFTBIGCOMPONENT         ,//12
 NOTBIGCOMPONENT         ,//13
 ORBIGCOMPONENT          ,//14
 PKVBIGCOMPONENT         ,//15
 RAISMALLCOMPONENT       ,//16
 PREGBIGCOMPONENT        ,//17
 REGBIGCOMPONENT         ,//18
 RPRBIGCOMPONENT         ,//19
 RPRSMALLCOMPONENT       ,//20
 SDIBIGCOMPONENT         ,//21
 SDISMALLCOMPONENT       ,//22
 VVBIGCOMPONENT          ,//23
 XORBIGCOMPONENT         ,//24
 YUSTBIGCOMPONENT        ,//25
 AISMALLCOMPONENT        ,//26
 QAISMALLCOMPONENT       ,//27
 PFBIGCOMPONENT          ,//28
 RDSBIGCOMPONENT         ,//29
 DFRESBIGCOMPONENT       ,//26
#if (((MODYFIKACIA_VERSII_PZ / 10) & 0x1) != 0)
 GOOSBIGCOMPONENT        ,//4
 MMSBIGCOMPONENT         ,//4
 LANBIGCOMPONENT         ,//4
#endif

#ifdef  MODYFIKACIA_VERSII_DS
 DOUTBIGDSCOMPONENT      ,//8
#endif
#if (                                \
     (MODYFIKACIA_VERSII_PZ == 8) || \
     (MODYFIKACIA_VERSII_PZ == 18)   \
    )
 DVOUTBIGCOMPONENT        ,//3
#endif

 TOTAL_COMPONENT         ,//26

 MARKER_OUTPERIMETR   = 100000,
 MARKER_ERRORPERIMETR = 100001,
 MARKER_ERRORDIAPAZON = 100002,
 MARKER_ERRORPAROL    = 100003
};

//макс размер буфера записи
#define MAXIMUMTW 128
//ошибка валидации
#define ERROR_VALID2 2
#define ERROR_VALID3 3

#endif
