#ifndef __CONST_MENU_CHOSE_SETTING_PROTECTION__
#define __CONST_MENU_CHOSE_SETTING_PROTECTION__

#define EKRAN_CHOOSE_SETTINGS_RPN (EKRAN_RESURS + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_RPN (EKRAN_CHOOSE_SETTINGS_RPN + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_RPN (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_RPN + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_RPN (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_RPN + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_RPN (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_RPN + 1)
#define EKRAN_CHOOSE_SETTINGS_ZSKH (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_RPN + 1)
#define EKRAN_CHOOSE_SETTINGS_BRP (EKRAN_CHOOSE_SETTINGS_ZSKH + 1)
#define EKRAN_CHOOSE_SETPOINT_GROUP1_BRP (EKRAN_CHOOSE_SETTINGS_BRP + 1)
#define EKRAN_CHOOSE_SETPOINT_GROUP2_BRP (EKRAN_CHOOSE_SETPOINT_GROUP1_BRP + 1)
#define EKRAN_CHOOSE_SETPOINT_GROUP3_BRP (EKRAN_CHOOSE_SETPOINT_GROUP2_BRP + 1)
#define EKRAN_CHOOSE_SETPOINT_GROUP4_BRP (EKRAN_CHOOSE_SETPOINT_GROUP3_BRP + 1)
#define EKRAN_CHOOSE_SETTINGS_ZNKh (EKRAN_CHOOSE_SETPOINT_GROUP4_BRP + 1)
#define EKRAN_CHOOSE_TIMEOUT_GROUP1_ZNKh (EKRAN_CHOOSE_SETTINGS_ZNKh + 1)
#define EKRAN_CHOOSE_TIMEOUT_GROUP2_ZNKh (EKRAN_CHOOSE_TIMEOUT_GROUP1_ZNKh + 1)
#define EKRAN_CHOOSE_TIMEOUT_GROUP3_ZNKh (EKRAN_CHOOSE_TIMEOUT_GROUP2_ZNKh + 1)
#define EKRAN_CHOOSE_TIMEOUT_GROUP4_ZNKh (EKRAN_CHOOSE_TIMEOUT_GROUP3_ZNKh + 1)
#define EKRAN_CHOOSE_SETTINGS_ZZ (EKRAN_CHOOSE_TIMEOUT_GROUP4_ZNKh + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_ZZ (EKRAN_CHOOSE_SETTINGS_ZZ + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_ZZ (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_ZZ + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_ZZ (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_ZZ + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_ZZ (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_ZZ + 1)
#define EKRAN_CHOOSE_SETTINGS_TZNP (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_ZZ + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_TZNP (EKRAN_CHOOSE_SETTINGS_TZNP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_TZNP (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_TZNP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_TZNP (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_TZNP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_TZNP (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_TZNP + 1)
#define EKRAN_CHOOSE_SETTINGS_APV (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_TZNP + 1)
#define EKRAN_CHOOSE_TIMEOUT_GROUP1_APV (EKRAN_CHOOSE_SETTINGS_APV + 1)
#define EKRAN_CHOOSE_TIMEOUT_GROUP2_APV (EKRAN_CHOOSE_TIMEOUT_GROUP1_APV + 1)
#define EKRAN_CHOOSE_TIMEOUT_GROUP3_APV (EKRAN_CHOOSE_TIMEOUT_GROUP2_APV + 1)
#define EKRAN_CHOOSE_TIMEOUT_GROUP4_APV (EKRAN_CHOOSE_TIMEOUT_GROUP3_APV + 1)
#define EKRAN_CHOOSE_SETTINGS_ACHR_CHAPV (EKRAN_CHOOSE_TIMEOUT_GROUP4_APV + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_ACHR_CHAPV (EKRAN_CHOOSE_SETTINGS_ACHR_CHAPV + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_ACHR_CHAPV (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_ACHR_CHAPV + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_ACHR_CHAPV (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_ACHR_CHAPV + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_ACHR_CHAPV (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_ACHR_CHAPV + 1)
#define EKRAN_CHOOSE_SETTINGS_UROV (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_ACHR_CHAPV + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_UROV (EKRAN_CHOOSE_SETTINGS_UROV + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_UROV (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_UROV + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_UROV (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_UROV + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_UROV (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_UROV + 1)
#define EKRAN_CHOOSE_SETTINGS_ZOP (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_UROV + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_ZOP (EKRAN_CHOOSE_SETTINGS_ZOP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_ZOP (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_ZOP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_ZOP (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_ZOP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_ZOP (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_ZOP + 1)
#define EKRAN_CHOOSE_SETTINGS_UMIN (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_ZOP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_UMIN (EKRAN_CHOOSE_SETTINGS_UMIN + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_UMIN (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_UMIN + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_UMIN (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_UMIN + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_UMIN (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_UMIN + 1)
#define EKRAN_CHOOSE_SETTINGS_UMAX (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_UMIN + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_UMAX (EKRAN_CHOOSE_SETTINGS_UMAX + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_UMAX (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_UMAX + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_UMAX (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_UMAX + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_UMAX (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_UMAX + 1)
#define EKRAN_CHOOSE_SETTINGS_UP (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_UMAX + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_UP (EKRAN_CHOOSE_SETTINGS_UP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_UP (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_UP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_UP (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_UP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_UP (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_UP + 1)
#define EKRAN_CHOOSE_SETTINGS_VMP (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_UP + 1)

#define MAX_ROW_FOR_CHOSE_SETTINGS_ANY_PROTECTION 3
#define MAX_ROW_FOR_CHOSE_SETTINGS_PROTECTION_WITH_TWO_GROUP (NUMBER_GROUP_USTAVOK + 1)
#define MAX_ROW_FOR_CHOSE_SETPOINTS_TIMEOUTS 2
#define MAX_ROW_FOR_CHOSE_SETTINGS_PROTECTION_WITH_CONTROL 1
#define MAX_ROW_FOR_CHOSE_SETTINGS_PROTECTION_WITH_SETPOINTS 1
#define MAX_ROW_FOR_CHOSE_SETTINGS_PROTECTION_WITH_TIMEOUT 1
#define MAX_ROW_FOR_CHOSE_SETTINGS_PROTECTION_WITH_TIMEOUT_CONTROL 2
#define MAX_ROW_FOR_CHOSE_SETTINGS_PROTECTION_WITH_SETPOINTS_CONTROL 2

#define INDEX_ML_GROUP1 0
#define INDEX_ML_GROUP2 1
#define INDEX_ML_GROUP3 2
#define INDEX_ML_GROUP4 3
#define INDEX_ML_CONTROL_WITH_GROUPS 4

//Це є основні позиції
#define INDEX_ML_SETPOINT 0
#define INDEX_ML_TIMEOUT 1
#define INDEX_ML_CONTROL 2

//Це є додаткові позиції, якщо вони не співпадають з основними
#define INDEX_ML_WITH_CONTROL_CONTROL 0
#define INDEX_ML_WITH_SETPOINT_SETPOINT 0
#define INDEX_ML_WITH_TIMEOUT_TIMEOUT 0
#define INDEX_ML_WITH_TIMEOUT_CONTROL_TIMEOUT 0
#define INDEX_ML_WITH_TIMEOUT_CONTROL_CONTROL 1
#define INDEX_ML_WITH_SETPOINT_CONTROL_SETPOINT 0
#define INDEX_ML_WITH_SETPOINT_CONTROL_CONTROL 1

#endif
