#ifndef __CONST_GLOBAL_TIMERS__
#define __CONST_GLOBAL_TIMERS__

//Величина, яка необхідна для періодичної (період 1  мс   ) генерації переривань каналом 1 таймеру 2 з прескаллером 2000 = (1999 + 1)
#define TIM2_CCR1_VAL 1000
#define TIM2_MIN_PERIOD_WRITE_READ 1 /*мкс*/
//Величина, яка необхідна для періодичної (період 10 мс   ) генерації переривань каналом 1 таймеру 4 з прескаллером 600 = (599 + 1)
#define TIM4_CCR1_VAL 1000
//Величина, яка необхідна для періодичної (період 1 мс   ) генерації переривань каналом 2 таймеру 4 з прескаллером 600 = (599 + 1)
#define TIM4_CCR2_VAL 100
//Величина, яка необхідна для періодичної (як мінімум, період 10 мкс   ) генерації переривань каналом 3 таймеру 4 з прескаллером 600 = (599 + 1)
#define TIM4_CCR3_VAL 1
//Величина, яка необхідна для періодичної (період 0,625 мс) генерації переривань каналом 1 таймеру 3 з прескаллером 1 = (0 + 1)
#define TIM5_CCR1_2_VAL 37500

#define DELTA_TIME_FOR_TIMERS 1
#define PERIOD_SIGNAL_OUTPUT_MODE_2 1000 /*мс*/

enum _index_timer
{
  INDEX_TIMER_INPUT_START = 0,

  _INDEX_TIMER_LOGIC_BEGIN = (INDEX_TIMER_INPUT_START + NUMBER_INPUTS),
  INDEX_TIMER_DF_PROLONG_SET_FOR_BUTTON_INTERFACE_START = _INDEX_TIMER_LOGIC_BEGIN,

  INDEX_TIMER_DF_PAUSE_START = (INDEX_TIMER_DF_PROLONG_SET_FOR_BUTTON_INTERFACE_START + NUMBER_DEFINED_FUNCTIONS),

  INDEX_TIMER_DF_WORK_START = (INDEX_TIMER_DF_PAUSE_START + NUMBER_DEFINED_FUNCTIONS),

  _INDEX_UMIN_BEGIN = (INDEX_TIMER_DF_WORK_START + NUMBER_DEFINED_FUNCTIONS),
  INDEX_TIMER_UMIN1 = _INDEX_UMIN_BEGIN,
  INDEX_TIMER_UMIN2,
  _INDEX_UMIN_END = INDEX_TIMER_UMIN2,

  _INDEX_UMAX_BEGIN,
  INDEX_TIMER_UMAX2 = _INDEX_UMAX_BEGIN,
  _INDEX_UMAX_END = INDEX_TIMER_UMAX2,

  _INDEX_ZNKh_BEGIN,
  INDEX_TIMER_ZNKh_PEREKL = _INDEX_ZNKh_BEGIN,
  INDEX_TIMER_ZNKh_TMP1,
  INDEX_TIMER_ZNKh_TMP2,
  _INDEX_ZNKh_END = INDEX_TIMER_ZNKh_TMP2,

  _INDEX_RPN_BEGIN,
  INDEX_TIMER_RPN_PEREKL = _INDEX_RPN_BEGIN,
  INDEX_TIMER_RPN_UB_PRYB,
  INDEX_TIMER_RPN_UB_PRYB_PRYSK,
  INDEX_TIMER_RPN_PRYSK_VID_UMAX,
  INDEX_TIMER_RPN_NESPR,
  INDEX_TIMER_RPN_TMP1,
  _INDEX_RPN_END = INDEX_TIMER_RPN_TMP1,

  _INDEX_UP_BEGIN,
  INDEX_TIMER_UP1 = _INDEX_UP_BEGIN,

  _INDEX_UP_END = (INDEX_TIMER_UP1 + NUMBER_UP - 1),

  _MAX_NUMBER_GLOBAL_TIMERS_WITHOUT_REGS,

  INDEX_TIMER_POSTFAULT = _MAX_NUMBER_GLOBAL_TIMERS_WITHOUT_REGS,
  INDEX_TIMER_FULL_AR_RECORD,

  INDEX_TIMER_DR_WORK,

  _MAX_NUMBER_GLOBAL_TIMERS
};

#endif
