#ifndef __CONST_MENU_CHOSE_TYPE_CONTROL_LOCATION__
#define __CONST_MENU_CHOSE_TYPE_CONTROL_LOCATION__

#define EKRAN_CHOOSE_SETTINGS_CONTROL_LOCATION (EKRAN_RANGUVANNJA_LED_17 + 1)
#define EKRAN_STP_CONTROL_LOCATION (EKRAN_CHOOSE_SETTINGS_CONTROL_LOCATION + 1)
#define EKRAN_CHOOSE_TYPE_CONTROL_LOCATION (EKRAN_STP_CONTROL_LOCATION + 1)
#define EKRAN_CALIBRATION_SELSYN (EKRAN_CHOOSE_TYPE_CONTROL_LOCATION + 1)

#define MAX_ROW_FOR_TYPE_CONTROL_LOCATION 1

enum _index__choose_settings_control_location
{
  INDEX_ML_STP_CONTROL_LOCATION = 0,
  INDEX_ML_TYPE_CONTROL_LOCATION,
  INDEX_ML_CALIBRATION_SELSYN,

  MAX_ROW_FOR_CHOSE_SETTINGS_CONTROL_LOCATION
};

enum index_ml_stp_control_location
{
  INDEX_ML_STP_TYPE_CTR_LOC_NUMBER_TOTAL = 0,
  INDEX_ML_STP_TYPE_CTR_LOC_NUMBER_NOMINAL,
  INDEX_ML_STP_TYPE_CTR_LOC_NUMBER_CURRENT,

  MAX_ROW_FOR_STP_CONTROL_LOCATION

};

enum _index_calibration_selsyn
{
  INDEX_ML_FIRST_LOCATION_SELSYN = 0,
  INDEX_ML_LAST_LOCATION_SELSYN,

  MAX_ROW_FOR_CALIBRATION_SELSYN

};

#define COL_NUMBER_STEPS_RPN_BEGIN 7
#define COL_NUMBER_STEPS_RPN_END 8

#endif
