#ifndef __CONST_MENU_RPN__
#define __CONST_MENU_RPN__

#define EKRAN_SETPOINT_RPN_GROUP1 (EKRAN_CHOSE_SETTINGS + 1)
#define EKRAN_SETPOINT_RPN_GROUP2 (EKRAN_SETPOINT_RPN_GROUP1 + 1)
#define EKRAN_SETPOINT_RPN_GROUP3 (EKRAN_SETPOINT_RPN_GROUP2 + 1)
#define EKRAN_SETPOINT_RPN_GROUP4 (EKRAN_SETPOINT_RPN_GROUP3 + 1)
#define EKRAN_TIMEOUT_RPN_GROUP1 (EKRAN_SETPOINT_UP_GROUP4 + 1)
#define EKRAN_TIMEOUT_RPN_GROUP2 (EKRAN_TIMEOUT_RPN_GROUP1 + 1)
#define EKRAN_TIMEOUT_RPN_GROUP3 (EKRAN_TIMEOUT_RPN_GROUP2 + 1)
#define EKRAN_TIMEOUT_RPN_GROUP4 (EKRAN_TIMEOUT_RPN_GROUP3 + 1)
#define EKRAN_CONTROL_RPN (EKRAN_TIMEOUT_UP_GROUP4 + 1)

enum _index_ml_stp_rpn
{
  WITHOUTZNAM_INDEX_ML_STPMTZ1 = 0,
  WITHOUTZNAM_INDEX_ML_STPMTZ1_N_VPERED,
  WITHOUTZNAM_INDEX_ML_STPMTZ1_N_NAZAD,
  WITHOUTZNAM_INDEX_ML_STPMTZ1_ANGLE,
  WITHOUTZNAM_INDEX_ML_STPMTZ1_PO_NAPRUZI,
  WITHOUTZNAM_INDEX_ML_STPMTZ1_U,

  WITHOUTZNAM_INDEX_ML_STPMTZ2,
  WITHOUTZNAM_INDEX_ML_STPMTZ2_N_VPERED,
  WITHOUTZNAM_INDEX_ML_STPMTZ2_N_NAZAD,
  WITHOUTZNAM_INDEX_ML_STPMTZ2_ANGLE,
  WITHOUTZNAM_INDEX_ML_STPMTZ2_PO_NAPRUZI,
  WITHOUTZNAM_INDEX_ML_STPMTZ2_U,

  WITHOUTZNAM_INDEX_ML_STPMTZ3,
  WITHOUTZNAM_INDEX_ML_STPMTZ3_N_VPERED,
  WITHOUTZNAM_INDEX_ML_STPMTZ3_N_NAZAD,
  WITHOUTZNAM_INDEX_ML_STPMTZ3_ANGLE,
  WITHOUTZNAM_INDEX_ML_STPMTZ3_PO_NAPRUZI,
  WITHOUTZNAM_INDEX_ML_STPMTZ3_U,

  WITHOUTZNAM_INDEX_ML_STPMTZ4,
  WITHOUTZNAM_INDEX_ML_STPMTZ4_N_VPERED,
  WITHOUTZNAM_INDEX_ML_STPMTZ4_N_NAZAD,
  WITHOUTZNAM_INDEX_ML_STPMTZ4_ANGLE,
  WITHOUTZNAM_INDEX_ML_STPMTZ4_PO_NAPRUZI,
  WITHOUTZNAM_INDEX_ML_STPMTZ4_U,

  MAX_ROW_FOR_SETPOINT_RPN
};

#define COL_SETPOINT_MTZ_1_BEGIN 3
#define COL_SETPOINT_MTZ_1_COMMA 6
#define COL_SETPOINT_MTZ_1_END 8

#define COL_SETPOINT_MTZ_1_N_VPERED_BEGIN 3
#define COL_SETPOINT_MTZ_1_N_VPERED_COMMA 6
#define COL_SETPOINT_MTZ_1_N_VPERED_END 8

#define COL_SETPOINT_MTZ_1_N_NAZAD_BEGIN 3
#define COL_SETPOINT_MTZ_1_N_NAZAD_COMMA 6
#define COL_SETPOINT_MTZ_1_N_NAZAD_END 8

#define COL_SETPOINT_MTZ_1_ANGLE_BEGIN 6
#define COL_SETPOINT_MTZ_1_ANGLE_END 7

#define COL_SETPOINT_MTZ_1_PO_NAPRUZI_BEGIN 3
#define COL_SETPOINT_MTZ_1_PO_NAPRUZI_COMMA 6
#define COL_SETPOINT_MTZ_1_PO_NAPRUZI_END 8

#define COL_SETPOINT_MTZ_1_U_BEGIN 3
#define COL_SETPOINT_MTZ_1_U_COMMA 6
#define COL_SETPOINT_MTZ_1_U_END 8

#define COL_SETPOINT_MTZ_1_K_BEGIN 5
#define COL_SETPOINT_MTZ_1_K_COMMA 8
#define COL_SETPOINT_MTZ_1_K_END 10

#define COL_SETPOINT_MTZ_2_BEGIN 3
#define COL_SETPOINT_MTZ_2_COMMA 6
#define COL_SETPOINT_MTZ_2_END 8

#define COL_SETPOINT_MTZ_2_N_VPERED_BEGIN 3
#define COL_SETPOINT_MTZ_2_N_VPERED_COMMA 6
#define COL_SETPOINT_MTZ_2_N_VPERED_END 8

#define COL_SETPOINT_MTZ_2_N_NAZAD_BEGIN 3
#define COL_SETPOINT_MTZ_2_N_NAZAD_COMMA 6
#define COL_SETPOINT_MTZ_2_N_NAZAD_END 8

#define COL_SETPOINT_MTZ_2_ANGLE_BEGIN 6
#define COL_SETPOINT_MTZ_2_ANGLE_END 7

#define COL_SETPOINT_MTZ_2_PO_NAPRUZI_BEGIN 3
#define COL_SETPOINT_MTZ_2_PO_NAPRUZI_COMMA 6
#define COL_SETPOINT_MTZ_2_PO_NAPRUZI_END 8

#define COL_SETPOINT_MTZ_2_U_BEGIN 3
#define COL_SETPOINT_MTZ_2_U_COMMA 6
#define COL_SETPOINT_MTZ_2_U_END 8

#define COL_SETPOINT_MTZ_2_K_BEGIN 5
#define COL_SETPOINT_MTZ_2_K_COMMA 8
#define COL_SETPOINT_MTZ_2_K_END 10

#define COL_SETPOINT_MTZ_3_BEGIN 3
#define COL_SETPOINT_MTZ_3_COMMA 6
#define COL_SETPOINT_MTZ_3_END 8

#define COL_SETPOINT_MTZ_3_N_VPERED_BEGIN 3
#define COL_SETPOINT_MTZ_3_N_VPERED_COMMA 6
#define COL_SETPOINT_MTZ_3_N_VPERED_END 8

#define COL_SETPOINT_MTZ_3_N_NAZAD_BEGIN 3
#define COL_SETPOINT_MTZ_3_N_NAZAD_COMMA 6
#define COL_SETPOINT_MTZ_3_N_NAZAD_END 8

#define COL_SETPOINT_MTZ_3_ANGLE_BEGIN 6
#define COL_SETPOINT_MTZ_3_ANGLE_END 7

#define COL_SETPOINT_MTZ_3_PO_NAPRUZI_BEGIN 3
#define COL_SETPOINT_MTZ_3_PO_NAPRUZI_COMMA 6
#define COL_SETPOINT_MTZ_3_PO_NAPRUZI_END 8

#define COL_SETPOINT_MTZ_3_U_BEGIN 3
#define COL_SETPOINT_MTZ_3_U_COMMA 6
#define COL_SETPOINT_MTZ_3_U_END 8

#define COL_SETPOINT_MTZ_3_K_BEGIN 5
#define COL_SETPOINT_MTZ_3_K_COMMA 8
#define COL_SETPOINT_MTZ_3_K_END 10

#define COL_SETPOINT_MTZ_4_BEGIN 3
#define COL_SETPOINT_MTZ_4_COMMA 6
#define COL_SETPOINT_MTZ_4_END 8

#define COL_SETPOINT_MTZ_4_N_VPERED_BEGIN 3
#define COL_SETPOINT_MTZ_4_N_VPERED_COMMA 6
#define COL_SETPOINT_MTZ_4_N_VPERED_END 8

#define COL_SETPOINT_MTZ_4_N_NAZAD_BEGIN 3
#define COL_SETPOINT_MTZ_4_N_NAZAD_COMMA 6
#define COL_SETPOINT_MTZ_4_N_NAZAD_END 8

#define COL_SETPOINT_MTZ_4_ANGLE_BEGIN 6
#define COL_SETPOINT_MTZ_4_ANGLE_END 7

#define COL_SETPOINT_MTZ_4_PO_NAPRUZI_BEGIN 3
#define COL_SETPOINT_MTZ_4_PO_NAPRUZI_COMMA 6
#define COL_SETPOINT_MTZ_4_PO_NAPRUZI_END 8

#define COL_SETPOINT_MTZ_4_U_BEGIN 3
#define COL_SETPOINT_MTZ_4_U_COMMA 6
#define COL_SETPOINT_MTZ_4_U_END 8

#define COL_SETPOINT_MTZ_4_K_BEGIN 5
#define COL_SETPOINT_MTZ_4_K_COMMA 8
#define COL_SETPOINT_MTZ_4_K_END 10

enum _index_ml_tmo_rpn
{
  WITHOUTZNAM_INDEX_ML_TMOMTZ1 = 0,
  WITHOUTZNAM_INDEX_ML_TMOMTZ1_N_VPERED,
  WITHOUTZNAM_INDEX_ML_TMOMTZ1_N_NAZAD,
  WITHOUTZNAM_INDEX_ML_TMOMTZ1_PO_NAPRUZI,

  WITHOUTZNAM_INDEX_ML_TMOMTZ2,
  WITHOUTZNAM_INDEX_ML_TMOMTZ2_PR,
  WITHOUTZNAM_INDEX_ML_TMOMTZ2_N_VPERED,
  WITHOUTZNAM_INDEX_ML_TMOMTZ2_N_VPERED_PR,
  WITHOUTZNAM_INDEX_ML_TMOMTZ2_N_NAZAD,
  WITHOUTZNAM_INDEX_ML_TMOMTZ2_N_NAZAD_PR,
  WITHOUTZNAM_INDEX_ML_TMOMTZ2_PO_NAPRUZI,
  WITHOUTZNAM_INDEX_ML_TMOMTZ2_PO_NAPRUZI_PR,
  WITHOUTZNAM_INDEX_ML_TMOMTZ2_VVID_PR,

  WITHOUTZNAM_INDEX_ML_TMOMTZ3,
  WITHOUTZNAM_INDEX_ML_TMOMTZ3_N_VPERED,
  WITHOUTZNAM_INDEX_ML_TMOMTZ3_N_NAZAD,
  WITHOUTZNAM_INDEX_ML_TMOMTZ3_PO_NAPRUZI,

  WITHOUTZNAM_INDEX_ML_TMOMTZ4,
  WITHOUTZNAM_INDEX_ML_TMOMTZ4_N_VPERED,
  WITHOUTZNAM_INDEX_ML_TMOMTZ4_N_NAZAD,
  WITHOUTZNAM_INDEX_ML_TMOMTZ4_PO_NAPRUZI,

  MAX_ROW_FOR_TIMEOUT_RPN
};

#define COL_TMO_MTZ_1_BEGIN 4
#define COL_TMO_MTZ_1_COMMA 6
#define COL_TMO_MTZ_1_END 8

#define COL_TMO_MTZ_1_N_VPERED_BEGIN 4
#define COL_TMO_MTZ_1_N_VPERED_COMMA 6
#define COL_TMO_MTZ_1_N_VPERED_END 8

#define COL_TMO_MTZ_1_N_NAZAD_BEGIN 4
#define COL_TMO_MTZ_1_N_NAZAD_COMMA 6
#define COL_TMO_MTZ_1_N_NAZAD_END 8

#define COL_TMO_MTZ_1_PO_NAPRUZI_BEGIN 4
#define COL_TMO_MTZ_1_PO_NAPRUZI_COMMA 6
#define COL_TMO_MTZ_1_PO_NAPRUZI_END 8

#define COL_TMO_MTZ_1_K_BEGIN 5
#define COL_TMO_MTZ_1_K_COMMA 8
#define COL_TMO_MTZ_1_K_END 10

#define COL_TMO_MTZ_2_BEGIN 3
#define COL_TMO_MTZ_2_COMMA 6
#define COL_TMO_MTZ_2_END 8

#define COL_TMO_MTZ_2_PR_BEGIN 5
#define COL_TMO_MTZ_2_PR_COMMA 6
#define COL_TMO_MTZ_2_PR_END 8

#define COL_TMO_MTZ_2_N_VPERED_BEGIN 3
#define COL_TMO_MTZ_2_N_VPERED_COMMA 6
#define COL_TMO_MTZ_2_N_VPERED_END 8

#define COL_TMO_MTZ_2_N_VPERED_PR_BEGIN 5
#define COL_TMO_MTZ_2_N_VPERED_PR_COMMA 6
#define COL_TMO_MTZ_2_N_VPERED_PR_END 8

#define COL_TMO_MTZ_2_N_NAZAD_BEGIN 3
#define COL_TMO_MTZ_2_N_NAZAD_COMMA 6
#define COL_TMO_MTZ_2_N_NAZAD_END 8

#define COL_TMO_MTZ_2_N_NAZAD_PR_BEGIN 5
#define COL_TMO_MTZ_2_N_NAZAD_PR_COMMA 6
#define COL_TMO_MTZ_2_N_NAZAD_PR_END 8

#define COL_TMO_MTZ_2_PO_NAPRUZI_BEGIN 3
#define COL_TMO_MTZ_2_PO_NAPRUZI_COMMA 6
#define COL_TMO_MTZ_2_PO_NAPRUZI_END 8

#define COL_TMO_MTZ_2_PO_NAPRUZI_PR_BEGIN 5
#define COL_TMO_MTZ_2_PO_NAPRUZI_PR_COMMA 6
#define COL_TMO_MTZ_2_PO_NAPRUZI_PR_END 8

#define COL_TMO_MTZ_2_VVID_PR_BEGIN 5
#define COL_TMO_MTZ_2_VVID_PR_COMMA 6
#define COL_TMO_MTZ_2_VVID_PR_END 8

#define COL_TMO_MTZ_2_K_BEGIN 5
#define COL_TMO_MTZ_2_K_COMMA 8
#define COL_TMO_MTZ_2_K_END 10

#define COL_TMO_MTZ_3_BEGIN 3
#define COL_TMO_MTZ_3_COMMA 6
#define COL_TMO_MTZ_3_END 8

#define COL_TMO_MTZ_3_N_VPERED_BEGIN 3
#define COL_TMO_MTZ_3_N_VPERED_COMMA 6
#define COL_TMO_MTZ_3_N_VPERED_END 8

#define COL_TMO_MTZ_3_N_NAZAD_BEGIN 3
#define COL_TMO_MTZ_3_N_NAZAD_COMMA 6
#define COL_TMO_MTZ_3_N_NAZAD_END 8

#define COL_TMO_MTZ_3_PO_NAPRUZI_BEGIN 3
#define COL_TMO_MTZ_3_PO_NAPRUZI_COMMA 6
#define COL_TMO_MTZ_3_PO_NAPRUZI_END 8

#define COL_TMO_MTZ_3_K_BEGIN 5
#define COL_TMO_MTZ_3_K_COMMA 8
#define COL_TMO_MTZ_3_K_END 10

#define COL_TMO_MTZ_4_BEGIN 3
#define COL_TMO_MTZ_4_COMMA 6
#define COL_TMO_MTZ_4_END 8

#define COL_TMO_MTZ_4_N_VPERED_BEGIN 3
#define COL_TMO_MTZ_4_N_VPERED_COMMA 6
#define COL_TMO_MTZ_4_N_VPERED_END 8

#define COL_TMO_MTZ_4_N_NAZAD_BEGIN 3
#define COL_TMO_MTZ_4_N_NAZAD_COMMA 6
#define COL_TMO_MTZ_4_N_NAZAD_END 8

#define COL_TMO_MTZ_4_PO_NAPRUZI_BEGIN 3
#define COL_TMO_MTZ_4_PO_NAPRUZI_COMMA 6
#define COL_TMO_MTZ_4_PO_NAPRUZI_END 8

#define COL_TMO_MTZ_4_K_BEGIN 5
#define COL_TMO_MTZ_4_K_COMMA 8
#define COL_TMO_MTZ_4_K_END 10

enum _index_ml_ctrl_rpn
{
  N_BIT_CTRMTZ_1 = 0,
  N_BIT_CTRMTZ_1_VPERED,
  N_BIT_CTRMTZ_1_NAZAD,
  N_BIT_CTRMTZ_1_ZNAM,
  N_BIT_CTRMTZ_1_ZNAM_TYPE,

  N_BIT_CTRMTZ_2,
  N_BIT_CTRMTZ_2_VPERED,
  N_BIT_CTRMTZ_2_NAZAD,
  N_BIT_CTRMTZ_2_PRYSKORENNJA,
  N_BIT_CTRMTZ_2_PRYSKORENA,
  N_BIT_CTRMTZ_2_ZNAM,
  N_BIT_CTRMTZ_2_ZNAM_TYPE,

  N_BIT_CTRMTZ_3,
  N_BIT_CTRMTZ_3_VPERED,
  N_BIT_CTRMTZ_3_NAZAD,
  N_BIT_CTRMTZ_3_ZNAM,
  N_BIT_CTRMTZ_3_ZNAM_TYPE,

  N_BIT_CTRMTZ_4,
  N_BIT_CTRMTZ_4_VPERED,
  N_BIT_CTRMTZ_4_NAZAD,
  N_BIT_CTRMTZ_4_ZNAM,
  N_BIT_CTRMTZ_4_ZNAM_TYPE,

  N_BIT_CTRMTZ_NESPR_KIL_NAPR,

  NUMBER_BITS_CTRRPN

};
#define CTR_MTZ_MASKA (MASKA_FOR_BIT(NUMBER_BITS_CTRRPN) - 1)

enum _index_ml_ctrl_msz_withoutznam
{
  WITHOUTZNAM_INDEX_ML_CTRMTZ_1 = 0,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_1_TYPE,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_1_VPERED,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_1_NAZAD,

  WITHOUTZNAM_INDEX_ML_CTRMTZ_2,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_2_TYPE,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_2_VPERED,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_2_NAZAD,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_2_PRYSKORENNJA,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_2_PRYSKORENA,

  WITHOUTZNAM_INDEX_ML_CTRMTZ_3,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_3_TYPE,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_3_VPERED,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_3_NAZAD,

  WITHOUTZNAM_INDEX_ML_CTRMTZ_4,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_4_TYPE,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_4_VPERED,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_4_NAZAD,

  WITHOUTZNAM_INDEX_ML_CTRMTZ_NESPR_KIL_NAPR,

  WITHOUTZNAM_MAX_ROW_FOR_CONTROL_MTZ
};

enum
{
  CTR_MTZ = 0,
  CTR_MTZ_VPERED,
  CTR_MTZ_NAZAD,
  CTR_MTZ_PRYSKORENNJA,
  CTR_MTZ_PRYSKORENA,
  CTR_MTZ_ZNAM,
  CTR_MTZ_ZNAM_TYPE,
  /*************************************/
  MTZ_CONST_MENU_SETTINGS_LENGTH
};

#endif
