#ifndef __CONST_SETPOINT_INTERVAL__
#define __CONST_SETPOINT_INTERVAL__

#define CONFIGURATION_WORK (MASKA_FOR_BIT(RPN_BIT_CONFIGURATION) |  \
                            MASKA_FOR_BIT(ZSKh_BIT_CONFIGURATION) | \
                            MASKA_FOR_BIT(ZNKh_BIT_CONFIGURATION) | \
                            MASKA_FOR_BIT(BRP_BIT_CONFIGURATION) |  \
                            MASKA_FOR_BIT(Umax_BIT_CONFIGURATION) | \
                            MASKA_FOR_BIT(Umin_BIT_CONFIGURATION) | \
                            MASKA_FOR_BIT(UP_BIT_CONFIGURATION))

#define KOEF_TT_MIN 1
#define KOEF_TT_MAX 600
#define KOEF_TT1_WORK 40
#define KOEF_TT2_WORK 30

#define KOEF_TN_MIN 30
#define KOEF_TN_MAX 350
#define KOEF_TN1_WORK 100
#define KOEF_TN2_WORK 350

#define SETPOINT_GRUPA_USTAVOK_MIN 1
#define SETPOINT_GRUPA_USTAVOK_MAX 4

#define TYPE_MTZ_SIMPLE 0
#define TYPE_MTZ_DIRECTIONAL 1
#define TYPE_MTZ_VOLTAGE 2
#define TYPE_MTZ_DEPENDENT_A 3
#define TYPE_MTZ_DEPENDENT_B 4
#define TYPE_MTZ_DEPENDENT_C 5
#define TYPE_MTZ_DEPENDENT_RT_80 6
#define TYPE_MTZ_DEPENDENT_RTV_I 7

#define SETPOINT_RPN_OSN_MIN 85000
#define SETPOINT_RPN_OSN_MAX 115000
#define SETPOINT_RPN_OSN_WORK 104000

#define SETPOINT_RPN_ZONY_MIN 100
#define SETPOINT_RPN_ZONY_MAX 500
#define SETPOINT_RPN_ZONY_WORK 300

#define SETPOINT_RPN_PER_MIN 3
#define SETPOINT_RPN_PER_MAX 32
#define SETPOINT_RPN_PER_UNLIMITED 0
#define SETPOINT_RPN_PER_WORK SETPOINT_RPN_PER_MIN

#define SETPOINT_RPN_DOD_MIN 85000
#define SETPOINT_RPN_DOD_MAX 115000
#define SETPOINT_RPN_DOD_WORK 104000

#define SETPOINT_RPN_K_MIN 0
#define SETPOINT_RPN_K_MAX 100
#define SETPOINT_RPN_K_WORK SETPOINT_RPN_K_MAX

#define TIMEOUT_RPN_UB_PRYB_MIN 1000
#define TIMEOUT_RPN_UB_PRYB_MAX 240000
#define TIMEOUT_RPN_UB_PRYB_WORK 18000

#define TIMEOUT_RPN_UB_PRYB_PRYSK_MIN 1000
#define TIMEOUT_RPN_UB_PRYB_PRYSK_MAX 240000
#define TIMEOUT_RPN_UB_PRYB_PRYSK_WORK 10000

#define TIMEOUT_RPN_UB_PRYSK_VID_UMAX_MIN 2000
#define TIMEOUT_RPN_UB_PRYSK_VID_UMAX_MAX 32000
#define TIMEOUT_RPN_UB_PRYSK_VID_UMAX_WORK 16000

#define TIMEOUT_RPN_PEREKL_MIN 1000
#define TIMEOUT_RPN_PEREKL_MAX 15000
#define TIMEOUT_RPN_PEREKL_WORK 8000

#define TIMEOUT_RPN_NESPR_MIN 500
#define TIMEOUT_RPN_NESPR_MAX 32000
#define TIMEOUT_RPN_NESPR_WORK 9000

#define CONTROL_RPN_WORK MASKA_FOR_BIT(INDEX_ML_CTRRPN_STATE)

#define CONTROL_ZSKh_WORK MASKA_FOR_BIT(INDEX_ML_CTRZSKh_STATE)

#define TIMEOUT_ZNKh_PEREKL_MIN 1500
#define TIMEOUT_ZNKh_PEREKL_MAX 32000
#define TIMEOUT_ZNKh_PEREKL_WORK TIMEOUT_ZNKh_PEREKL_MIN

#define CONTROL_ZNKh_WORK MASKA_FOR_BIT(INDEX_ML_CTRZNKh_STATE)

#define SETPOINT_BRP_I_BLK_MIN 4000
#define SETPOINT_BRP_I_BLK_MAX 10000
#define SETPOINT_BRP_I_BLK_WORK SETPOINT_BRP_I_BLK_MIN

#define CONTROL_BRP_WORK 0

#define SETPOINT_UMIN1_MIN 0
#define SETPOINT_UMIN1_MAX 100000
#define SETPOINT_UMIN1_WORK 80000

#define SETPOINT_UMIN2_MIN 0
#define SETPOINT_UMIN2_MAX 100000
#define SETPOINT_UMIN2_WORK SETPOINT_UMIN2_MIN

#define TIMEOUT_UMIN1_MIN 0
#define TIMEOUT_UMIN1_MAX 32000
#define TIMEOUT_UMIN1_WORK TIMEOUT_UMIN1_MIN

#define TIMEOUT_UMIN2_MIN 0
#define TIMEOUT_UMIN2_MAX 32000
#define TIMEOUT_UMIN2_WORK TIMEOUT_UMIN2_MIN

#define CONTROL_UMIN_WORK MASKA_FOR_BIT(INDEX_ML_CTRUmin_STAGE_1)

#define SETPOINT_UMAX1_MIN 110000
#define SETPOINT_UMAX1_MAX 120000
#define SETPOINT_UMAX1_WORK 115000

#define SETPOINT_UMAX2_MIN 100000
#define SETPOINT_UMAX2_MAX 120000
#define SETPOINT_UMAX2_WORK SETPOINT_UMAX2_MIN

#define TIMEOUT_UMAX2_MIN 100
#define TIMEOUT_UMAX2_MAX 32000
#define TIMEOUT_UMAX2_WORK TIMEOUT_UMAX2_MIN

#define CONTROL_UMAX_WORK 0

#define SETPOINT_UP_I_MIN 500
#define SETPOINT_UP_I_MAX 150000

#define SETPOINT_UP_3I0_MIN 10
#define SETPOINT_UP_3I0_MAX 2000

#define SETPOINT_UP_U_MIN 5000
#define SETPOINT_UP_U_MAX 140000

#define SETPOINT_UP_P_MIN 10
#define SETPOINT_UP_P_MAX 2000000

#define SETPOINT_UP_KP_MORE_MIN 50
#define SETPOINT_UP_KP_MORE_MAX 95

#define SETPOINT_UP_KP_LESS_MIN 105
#define SETPOINT_UP_KP_LESS_MAX 150

#define TIMEOUT_UP_MIN 0
#define TIMEOUT_UP_MAX 600000

#define NUMBER_STEPS_RPN_MIN 2
#define NUMBER_STEPS_RPN_MAX 60
#define NUMBER_STEPS_RPN_WORK 7

#define NUMBER_STEPS_RPN_UNDEFINED -1
#define LOCATION_RPN_MIN 1

#define LOCATION_RPN_WORK 5

#define MAX_TYPE_CONTROL_LOCATION 3
#define VALUE_TYPE_CONTROL_LOCATION_MIN 0
#define VALUE_TYPE_CONTROL_LOCATION_MAX (MAX_TYPE_CONTROL_LOCATION - 1)
#define VALUE_TYPE_CONTROL_LOCATION_WORK 1

#define KOEF_DOPUSK_DV_POST_MIN 0
#define KOEF_DOPUSK_DV_ZMIN_MIN 20
#define KOEF_DOPUSK_DV_MAX 60

#define TIMEOUT_DEACTIVATION_PASSWORD_OFF 0
#define TIMEOUT_DEACTIVATION_PASSWORD_MIN 30
#define TIMEOUT_DEACTIVATION_PASSWORD_MAX 3600

#define TIMEOUT_NEW_SETTINGS_MIN 60
#define TIMEOUT_NEW_SETTINGS_MAX 3600

#define KOEF_ADDRESS_MIN 1
#define KOEF_ADDRESS_MAX 247

#define NETWORK_MASK_MIN 8
#define NETWORK_MASK_DEFAULT 24
#define NETWORK_MASK_MAX 32

#define NETWORK_PORT_MIN 0
#define NETWORK_PORT_MAX 65535

#define NETWORK_PERIOD_SYNC_MIN 0
#define NETWORK_PERIOD_SYNC_MAX 65535

#define TIME_ZONE_MIN (-11)
#define TIME_ZONE_MAX 12

#define DST_RULE_MM_MIN _Jan
#define DST_RULE_MM_MAX _Dec

#define DST_RULE_DOW_MIN _Sun
#define DST_RULE_DOW_MAX _Sat

#define DST_RULE_WR_MIN _N1
#define DST_RULE_WR_MAX _NL

#define DST_RULE_HH_MIN 0
#define DST_RULE_HH_MAX 23

#define MAX_NUMBER_SPEEDS_INTERFACE 7
#define VALUE_SPEED_INTERFACE_MIN 0
#define VALUE_SPEED_INTERFACE_MAX (MAX_NUMBER_SPEEDS_INTERFACE - 1)

#define MAX_NUMBER_PARE_INTERFACE 3
#define VALUE_PARE_INTERFACE_MIN 0
#define VALUE_PARE_INTERFACE_MAX (MAX_NUMBER_PARE_INTERFACE - 1)

#define MAX_NUMBER_STOP_BITS_INTERFACE 2
#define VALUE_STOP_BITS_INTERFACE_MIN 0
#define VALUE_STOP_BITS_INTERFACE_MAX (MAX_NUMBER_STOP_BITS_INTERFACE - 1)

#define VALUE_TIME_OUT_1_INTERFACE_MIN 15
#define VALUE_TIME_OUT_1_INTERFACE_MAX 694

#define VALUE_SETTING_LANGUAGE_MIN LANGUAGE_RU
#define VALUE_SETTING_LANGUAGE_MAX LANGUAGE_EN

#define NUMBER_ITERATION_EL_MIN 1
#define NUMBER_ITERATION_EL_MAX 32

#define NUMBER_DEFINED_FUNCTIONS_MIN 0
#define NUMBER_DEFINED_FUNCTIONS_MAX NUMBER_DEFINED_FUNCTIONS

#define NUMBER_DEFINED_TRIGGERS_MIN 0
#define NUMBER_DEFINED_TRIGGERS_MAX NUMBER_DEFINED_TRIGGERS

#define NUMBER_DEFINED_AND_MIN 0
#define NUMBER_DEFINED_AND_MAX NUMBER_DEFINED_AND

#define NUMBER_DEFINED_OR_MIN 0
#define NUMBER_DEFINED_OR_MAX NUMBER_DEFINED_OR

#define NUMBER_DEFINED_XOR_MIN 0
#define NUMBER_DEFINED_XOR_MAX NUMBER_DEFINED_XOR

#define NUMBER_DEFINED_NOT_MIN 0
#define NUMBER_DEFINED_NOT_MAX NUMBER_DEFINED_NOT

#define TIMEOUT_DF_PAUSE_MIN 0
#define TIMEOUT_DF_PAUSE_MAX 600000

#define TIMEOUT_DF_WORK_MIN 0
#define TIMEOUT_DF_WORK_MAX 600000

#define TIMEOUT_DR_ELONGATION_MIN 0
#define TIMEOUT_DR_ELONGATION_MAX 600000

#define TIMEOUT_PREFAULT_MIN 100
#define TIMEOUT_PREFAULT_MAX 5000
#define TIMEOUT_PREFAULT_WORK TIMEOUT_PREFAULT_MIN

#define TIMEOUT_POSTFAULT_MIN 100
#define TIMEOUT_POSTFAULT_MAX 15000
#define TIMEOUT_POSTFAULT_WORK TIMEOUT_POSTFAULT_MIN

#define TIMEOUT_DISKRETN_MIN (NUMBER_PEROPD_USEREDNENNJA * 20)
#define TIMEOUT_DISKRETN_MAX (10 * TIMEOUT_DISKRETN_MIN)
#define TIMEOUT_DISKRETN_WORK TIMEOUT_DISKRETN_MIN

#endif
