#ifndef __CONST_MENU_TRANSFORMATOR__
#define __CONST_MENU_TRANSFORMATOR__

#define EKRAN_TRANSFORMATOR_INFO (EKRAN_LIST_LEDS_FOR_RANGUVANNJA + 1)

enum _index_ml_stp_transformator
{
  INDEX_ML_TT1 = 0,
  INDEX_ML_TT2,
  INDEX_ML_TN1,
  INDEX_ML_TN2,

  MAX_ROW_FOR_TRANSFORMATOR_INFO
};

#define COL_TT_BEGIN 5
#define COL_TT_END 8

#define COL_TN_BEGIN 5
#define COL_TN_END 8

#endif
