#ifndef __CONST_MENU_BRP__
#define __CONST_MENU_BRP__

#define EKRAN_SETPOINT_BRP_GROUP1 (EKRAN_SETPOINT_RPN_GROUP4 + 1)
#define EKRAN_SETPOINT_BRP_GROUP2 (EKRAN_SETPOINT_BRP_GROUP1 + 1)
#define EKRAN_SETPOINT_BRP_GROUP3 (EKRAN_SETPOINT_BRP_GROUP2 + 1)
#define EKRAN_SETPOINT_BRP_GROUP4 (EKRAN_SETPOINT_BRP_GROUP3 + 1)
#define EKRAN_CONTROL_BRP (EKRAN_CONTROL_SZKh + 1)

enum _index_ml_stp_brp
{
  INDEX_ML_STPBRP_I_BLK = 0,

  MAX_ROW_FOR_SETPOINT_BRP
};

#define COL_SETPOINT_BRP_I_BLK_BEGIN 5
#define COL_SETPOINT_BRP_I_BLK_COMMA 7
#define COL_SETPOINT_BRP_I_BLK_END 8

enum _index_ml_ctrl_brp
{
  INDEX_ML_CTRBRP_STATE = 0,

  MAX_ROW_FOR_CONTROL_BRP
};

#define CTR_BRP_MASKA (MASKA_FOR_BIT(MAX_ROW_FOR_CONTROL_BRP) - 1)

#endif
