#ifndef __CONST_MENU_RPN__
#define __CONST_MENU_RPN__

#define EKRAN_SETPOINT_RPN_GROUP1 (EKRAN_CHOSE_SETTINGS + 1)
#define EKRAN_SETPOINT_RPN_GROUP2 (EKRAN_SETPOINT_RPN_GROUP1 + 1)
#define EKRAN_SETPOINT_RPN_GROUP3 (EKRAN_SETPOINT_RPN_GROUP2 + 1)
#define EKRAN_SETPOINT_RPN_GROUP4 (EKRAN_SETPOINT_RPN_GROUP3 + 1)
#define EKRAN_TIMEOUT_RPN_GROUP1 (EKRAN_SETPOINT_UP_GROUP4 + 1)
#define EKRAN_TIMEOUT_RPN_GROUP2 (EKRAN_TIMEOUT_RPN_GROUP1 + 1)
#define EKRAN_TIMEOUT_RPN_GROUP3 (EKRAN_TIMEOUT_RPN_GROUP2 + 1)
#define EKRAN_TIMEOUT_RPN_GROUP4 (EKRAN_TIMEOUT_RPN_GROUP3 + 1)
#define EKRAN_CONTROL_RPN (EKRAN_TIMEOUT_UP_GROUP4 + 1)

enum _index_ml_stp_rpn
{
  INDEX_ML_STPRPN_OSN = 0,
  INDEX_ML_STPRPN_ZONE,
  INDEX_ML_STPRPN_MAX_PER,
  INDEX_ML_STPRPN_DOD,
  INDEX_ML_STPRPN_K,

  MAX_ROW_FOR_SETPOINT_RPN
};

#define COL_SETPOINT_RPN_OSN_BEGIN 4
#define COL_SETPOINT_RPN_OSN_COMMA 7
#define COL_SETPOINT_RPN_OSN_END 8

#define COL_SETPOINT_RPN_ZONE_BEGIN 5
#define COL_SETPOINT_RPN_ZONE_COMMA 6
#define COL_SETPOINT_RPN_ZONE_END 7

#define COL_SETPOINT_RPN_MAX_PER_BEGIN 7
#define COL_SETPOINT_RPN_MAX_PER_END 8

#define COL_SETPOINT_RPN_DOD_BEGIN 4
#define COL_SETPOINT_RPN_DOD_COMMA 7
#define COL_SETPOINT_RPN_DOD_END 8

#define COL_SETPOINT_RPN_K_BEGIN 6
#define COL_SETPOINT_RPN_K_COMMA 7
#define COL_SETPOINT_RPN_K_END 9

enum _index_ml_tmo_rpn
{
  INDEX_ML_TMORPN_UB_PRYB = 0,
  INDEX_ML_TMORPN_UB_PRYB_PRYSK,
  INDEX_ML_TMORPN_PRYSK_VID_UMAX,
  INDEX_ML_TMORPN_PEREKL,
  INDEX_ML_TMORPN_NESPR,

  MAX_ROW_FOR_TIMEOUT_RPN
};

#define COL_TMO_RPN_UB_PRYB_BEGIN 5
#define COL_TMO_RPN_UB_PRYB_END 7

#define COL_TMO_RPN_UB_PRYB_PRYSK_BEGIN 5
#define COL_TMO_RPN_UB_PRYB_PRYSK_END 7

#define COL_TMO_RPN_PRYSK_VID_UMAX_BEGIN 5
#define COL_TMO_RPN_PRYSK_VID_UMAX_COMMA 7
#define COL_TMO_RPN_PRYSK_VID_UMAX_END 8

#define COL_TMO_RPN_PEREKL_BEGIN 4
#define COL_TMO_RPN_PEREKL_COMMA 6
#define COL_TMO_RPN_PEREKL_END 8

#define COL_TMO_RPN_NESPR_BEGIN 4
#define COL_TMO_RPN_NESPR_COMMA 6
#define COL_TMO_RPN_NESPR_END 8

enum _index_ml_ctrl_rpn
{
  N_BIT_CTRMTZ_1 = 0,
  N_BIT_CTRMTZ_1_VPERED,
  N_BIT_CTRMTZ_1_NAZAD,
  N_BIT_CTRMTZ_1_ZNAM,
  N_BIT_CTRMTZ_1_ZNAM_TYPE,

  N_BIT_CTRMTZ_2,
  N_BIT_CTRMTZ_2_VPERED,
  N_BIT_CTRMTZ_2_NAZAD,
  N_BIT_CTRMTZ_2_PRYSKORENNJA,
  N_BIT_CTRMTZ_2_PRYSKORENA,
  N_BIT_CTRMTZ_2_ZNAM,
  N_BIT_CTRMTZ_2_ZNAM_TYPE,

  N_BIT_CTRMTZ_3,
  N_BIT_CTRMTZ_3_VPERED,
  N_BIT_CTRMTZ_3_NAZAD,
  N_BIT_CTRMTZ_3_ZNAM,
  N_BIT_CTRMTZ_3_ZNAM_TYPE,

  N_BIT_CTRMTZ_4,
  N_BIT_CTRMTZ_4_VPERED,
  N_BIT_CTRMTZ_4_NAZAD,
  N_BIT_CTRMTZ_4_ZNAM,
  N_BIT_CTRMTZ_4_ZNAM_TYPE,

  N_BIT_CTRMTZ_NESPR_KIL_NAPR,

  NUMBER_BITS_CTRRPN

};
#define CTR_MTZ_MASKA (MASKA_FOR_BIT(NUMBER_BITS_CTRRPN) - 1)

enum _index_ml_ctrl_msz_withoutznam
{
  WITHOUTZNAM_INDEX_ML_CTRMTZ_1 = 0,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_1_TYPE,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_1_VPERED,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_1_NAZAD,

  WITHOUTZNAM_INDEX_ML_CTRMTZ_2,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_2_TYPE,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_2_VPERED,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_2_NAZAD,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_2_PRYSKORENNJA,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_2_PRYSKORENA,

  WITHOUTZNAM_INDEX_ML_CTRMTZ_3,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_3_TYPE,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_3_VPERED,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_3_NAZAD,

  WITHOUTZNAM_INDEX_ML_CTRMTZ_4,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_4_TYPE,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_4_VPERED,
  WITHOUTZNAM_INDEX_ML_CTRMTZ_4_NAZAD,

  WITHOUTZNAM_INDEX_ML_CTRMTZ_NESPR_KIL_NAPR,

  WITHOUTZNAM_MAX_ROW_FOR_CONTROL_MTZ
};

#endif
