#ifndef __CONST_MENU_UMIN__
#define __CONST_MENU_UMIN__

#define EKRAN_SETPOINT_UMIN_GROUP1 (EKRAN_SETPOINT_BRP_GROUP4 + 1)
#define EKRAN_SETPOINT_UMIN_GROUP2 (EKRAN_SETPOINT_UMIN_GROUP1 + 1)
#define EKRAN_SETPOINT_UMIN_GROUP3 (EKRAN_SETPOINT_UMIN_GROUP2 + 1)
#define EKRAN_SETPOINT_UMIN_GROUP4 (EKRAN_SETPOINT_UMIN_GROUP3 + 1)
#define EKRAN_TIMEOUT_UMIN_GROUP1 (EKRAN_TIMEOUT_RPN_GROUP4 + 1)
#define EKRAN_TIMEOUT_UMIN_GROUP2 (EKRAN_TIMEOUT_UMIN_GROUP1 + 1)
#define EKRAN_TIMEOUT_UMIN_GROUP3 (EKRAN_TIMEOUT_UMIN_GROUP2 + 1)
#define EKRAN_TIMEOUT_UMIN_GROUP4 (EKRAN_TIMEOUT_UMIN_GROUP3 + 1)
#define EKRAN_CONTROL_UMIN (EKRAN_CONTROL_ZNKh + 1)

enum _index_ml_stp_Umin
{
  INDEX_ML_STPUmin_Umin1 = 0,
  INDEX_ML_STPUmin_Umin2,

  MAX_ROW_FOR_SETPOINT_UMIN
};

#define COL_SETPOINT_Umin_Umin1_BEGIN 5
#define COL_SETPOINT_Umin_Umin1_END 7

#define COL_SETPOINT_Umin_Umin2_BEGIN 5
#define COL_SETPOINT_Umin_Umin2_END 7

enum _index_ml_tmo_Umin
{
  INDEX_ML_TMOUmin_Umin1 = 0,
  INDEX_ML_TMOUmin_Umin2,

  MAX_ROW_FOR_TIMEOUT_UMIN
};

#define COL_TMO_Umin_Umin1_BEGIN 5
#define COL_TMO_Umin_Umin1_COMMA 7
#define COL_TMO_Umin_Umin1_END 8

#define COL_TMO_Umin_Umin2_BEGIN 5
#define COL_TMO_Umin_Umin2_COMMA 7
#define COL_TMO_Umin_Umin2_END 8

enum _index_ml_ctrl_Umin
{
  INDEX_ML_CTRUmin_STAGE_1 = 0,
  INDEX_ML_CTRUmin_STAGE_2,

  MAX_ROW_FOR_CONTROL_UMIN
};

#define CTR_UMIN_MASKA (MASKA_FOR_BIT(MAX_ROW_FOR_CONTROL_UMIN) - 1)

#endif
