#ifndef __CONST_SETPOINT_INTERVAL__
#define __CONST_SETPOINT_INTERVAL__

#define CONFIGURATION_WORK (MASKA_FOR_BIT(RPN_BIT_CONFIGURATION) |  \
                            MASKA_FOR_BIT(ZSKh_BIT_CONFIGURATION) | \
                            MASKA_FOR_BIT(ZNKh_BIT_CONFIGURATION) | \
                            MASKA_FOR_BIT(BRP_BIT_CONFIGURATION) |  \
                            MASKA_FOR_BIT(Umax_BIT_CONFIGURATION) | \
                            MASKA_FOR_BIT(Umin_BIT_CONFIGURATION))

#define KOEF_TO_MIN 1
#define KOEF_TO_MAX 150

#define KOEF_TT_MIN 1
#define KOEF_TT_MAX 2000

#define KOEF_TT04_MIN 1
#define KOEF_TT04_MAX 2000

#define KOEF_TN_MIN 50
#define KOEF_TN_MAX 1800

#define SETPOINT_GRUPA_USTAVOK_MIN 1
#define SETPOINT_GRUPA_USTAVOK_MAX 4

#define TYPE_MTZ_SIMPLE 0
#define TYPE_MTZ_DIRECTIONAL 1
#define TYPE_MTZ_VOLTAGE 2
#define TYPE_MTZ_DEPENDENT_A 3
#define TYPE_MTZ_DEPENDENT_B 4
#define TYPE_MTZ_DEPENDENT_C 5
#define TYPE_MTZ_DEPENDENT_RT_80 6
#define TYPE_MTZ_DEPENDENT_RTV_I 7

#define SETPOINT_RPN_OSN_MIN 85000
#define SETPOINT_RPN_OSN_MAX 115000
#define SETPOINT_RPN_OSN_WORK 104000

#define SETPOINT_RPN_ZONY_MIN 100
#define SETPOINT_RPN_ZONY_MAX 500
#define SETPOINT_RPN_ZONY_WORK 300

#define SETPOINT_RPN_PER_MIN 3
#define SETPOINT_RPN_PER_MAX 32
#define SETPOINT_RPN_PER_UNLIMITED 0
#define SETPOINT_RPN_PER_WORK SETPOINT_RPN_PER_MIN

#define SETPOINT_RPN_DOD_MIN 0
#define SETPOINT_RPN_DOD_MAX 90
#define SETPOINT_RPN_DOD_WORK 104000

#define SETPOINT_RPN_K_MIN 0
#define SETPOINT_RPN_K_MAX 100
#define SETPOINT_RPN_K_WORK SETPOINT_RPN_K_MAX

#define TIMEOUT_RPN_UB_PRYB_MIN 1000
#define TIMEOUT_RPN_UB_PRYB_MAX 240000
#define TIMEOUT_RPN_UB_PRYB_WORK 18000

#define TIMEOUT_RPN_UB_PRYB_PRYSK_MIN 1000
#define TIMEOUT_RPN_UB_PRYB_PRYSK_MAX 240000
#define TIMEOUT_RPN_UB_PRYB_PRYSK_WORK 10000

#define TIMEOUT_RPN_UB_PRYSK_VID_UMAX_MIN 2000
#define TIMEOUT_RPN_UB_PRYSK_VID_UMAX_MAX 32000
#define TIMEOUT_RPN_UB_PRYSK_VID_UMAX_WORK 16000

#define TIMEOUT_RPN_PEREKL_MIN 1000
#define TIMEOUT_RPN_PEREKL_MAX 15000
#define TIMEOUT_RPN_PEREKL_WORK 8000

#define TIMEOUT_RPN_NESPR_MIN 500
#define TIMEOUT_RPN_NESPR_MAX 32000
#define TIMEOUT_RPN_NESPR_WORK 9000

#define CONTROL_RPN_WORK MASKA_FOR_BIT(INDEX_ML_CTRRPN_STATE)

#define CONTROL_ZSKh_WORK MASKA_FOR_BIT(INDEX_ML_CTRZSKh_STATE)

#define TIMEOUT_ZNKh_PEREKL_MIN 1500
#define TIMEOUT_ZNKh_PEREKL_MAX 32000
#define TIMEOUT_ZNKh_PEREKL_WORK TIMEOUT_ZNKh_PEREKL_MIN

#define CONTROL_ZNKh_WORK MASKA_FOR_BIT(INDEX_ML_CTRZNKh_STATE)

#define SETPOINT_BRP_I_BLK_MIN 4000
#define SETPOINT_BRP_I_BLK_MAX 10000
#define SETPOINT_BRP_I_BLK_WORK SETPOINT_BRP_I_BLK_MIN

#define CONTROL_BRP_WORK 0

#define SETPOINT_ZOP_MIN 10
#define SETPOINT_ZOP_MAX 1000

#define TIMEOUT_ZOP_MIN 0
#define TIMEOUT_ZOP_MAX 32000

#define SETPOINT_UMIN1_MIN 5000
#define SETPOINT_UMIN1_MAX 110000

#define SETPOINT_UMIN1_IBLK_MIN 250
#define SETPOINT_UMIN1_IBLK_MAX 5000

#define SETPOINT_UMIN2_MIN 5000
#define SETPOINT_UMIN2_MAX 110000

#define SETPOINT_UMIN2_IBLK_MIN 250
#define SETPOINT_UMIN2_IBLK_MAX 5000

#define TIMEOUT_UMIN1_MIN 100
#define TIMEOUT_UMIN1_MAX 32000

#define TIMEOUT_UMIN2_MIN 100
#define TIMEOUT_UMIN2_MAX 32000

#define SETPOINT_UMAX1_MIN 23000
#define SETPOINT_UMAX1_MAX 140000

#define SETPOINT_UMAX2_MIN 23000
#define SETPOINT_UMAX2_MAX 140000

#define SETPOINT_KP_UMAX_MIN 50
#define SETPOINT_KP_UMAX_DEFAULT 95
#define SETPOINT_KP_UMAX_MAX 96

#define TIMEOUT_UMAX1_MIN 0
#define TIMEOUT_UMAX1_MAX 600000

#define TIMEOUT_UMAX2_MIN 0
#define TIMEOUT_UMAX2_MAX 600000

#define SETPOINT_UP_I_MIN 500
#define SETPOINT_UP_I_MAX 150000

#define SETPOINT_UP_3I0_MIN 10
#define SETPOINT_UP_3I0_MAX 2000

#define SETPOINT_UP_U_MIN 5000
#define SETPOINT_UP_U_MAX 140000

#define SETPOINT_UP_P_MIN 10
#define SETPOINT_UP_P_MAX 2000000

#define SETPOINT_UP_KP_MORE_MIN 50
#define SETPOINT_UP_KP_MORE_MAX 95

#define SETPOINT_UP_KP_LESS_MIN 105
#define SETPOINT_UP_KP_LESS_MAX 150

#define TIMEOUT_UP_MIN 0
#define TIMEOUT_UP_MAX 600000

#define SETPOINT_Inom_MIN 5
#define SETPOINT_Inom_MAX (SETPOINT_Inom_MIN * KOEF_TT_MAX)

#define SETPOINT_RKS_Inom_MIN 1000
#define SETPOINT_RKS_Inom_MAX 100000

#define SETPOINT_Inom_vymk_MIN 100
#define SETPOINT_Inom_vymk_MAX 50000

#define SETPOINT_RKS_Inom_vymk_MIN 10
#define SETPOINT_RKS_Inom_vymk_MAX 999

#define TIMEOUT_SWCH_ON_MIN 150
#define TIMEOUT_SWCH_ON_MAX 5000

#define TIMEOUT_SWCH_OFF_MIN 150
#define TIMEOUT_SWCH_OFF_MAX 5000

#define TIMEOUT_SWCH_UDL_BLK_ON_MIN 0
#define TIMEOUT_SWCH_UDL_BLK_ON_MAX 32000

#define TIMEOUT_PRYVODA_VV_MIN 150
#define TIMEOUT_PRYVODA_VV_MAX 1000

#define KOEF_DOPUSK_DV_POST_MIN 0
#define KOEF_DOPUSK_DV_ZMIN_MIN 20
#define KOEF_DOPUSK_DV_MAX 60

#define TIMEOUT_DEACTIVATION_PASSWORD_OFF 0
#define TIMEOUT_DEACTIVATION_PASSWORD_MIN 30
#define TIMEOUT_DEACTIVATION_PASSWORD_MAX 3600

#define TIMEOUT_NEW_SETTINGS_MIN 60
#define TIMEOUT_NEW_SETTINGS_MAX 3600

#define KOEF_ADDRESS_MIN 1
#define KOEF_ADDRESS_MAX 247

#define NETWORK_MASK_MIN 8
#define NETWORK_MASK_DEFAULT 24
#define NETWORK_MASK_MAX 32

#define NETWORK_PORT_MIN 0
#define NETWORK_PORT_MAX 65535

#define NETWORK_PERIOD_SYNC_MIN 0
#define NETWORK_PERIOD_SYNC_MAX 65535

#define TIME_ZONE_MIN (-11)
#define TIME_ZONE_MAX 12

#define DST_RULE_MM_MIN _Jan
#define DST_RULE_MM_MAX _Dec

#define DST_RULE_DOW_MIN _Sun
#define DST_RULE_DOW_MAX _Sat

#define DST_RULE_WR_MIN _N1
#define DST_RULE_WR_MAX _NL

#define DST_RULE_HH_MIN 0
#define DST_RULE_HH_MAX 23

#define MAX_NUMBER_SPEEDS_INTERFACE 7
#define VALUE_SPEED_INTERFACE_MIN 0
#define VALUE_SPEED_INTERFACE_MAX (MAX_NUMBER_SPEEDS_INTERFACE - 1)

#define MAX_NUMBER_PARE_INTERFACE 3
#define VALUE_PARE_INTERFACE_MIN 0
#define VALUE_PARE_INTERFACE_MAX (MAX_NUMBER_PARE_INTERFACE - 1)

#define MAX_NUMBER_STOP_BITS_INTERFACE 2
#define VALUE_STOP_BITS_INTERFACE_MIN 0
#define VALUE_STOP_BITS_INTERFACE_MAX (MAX_NUMBER_STOP_BITS_INTERFACE - 1)

#define VALUE_TIME_OUT_1_INTERFACE_MIN 15
#define VALUE_TIME_OUT_1_INTERFACE_MAX 694

#define VALUE_SETTING_LANGUAGE_MIN LANGUAGE_RU
#define VALUE_SETTING_LANGUAGE_MAX LANGUAGE_EN

#define NUMBER_ITERATION_EL_MIN 1
#define NUMBER_ITERATION_EL_MAX 32

#define NUMBER_DEFINED_FUNCTIONS_MIN 0
#define NUMBER_DEFINED_FUNCTIONS_MAX NUMBER_DEFINED_FUNCTIONS

#define NUMBER_DEFINED_TRIGGERS_MIN 0
#define NUMBER_DEFINED_TRIGGERS_MAX NUMBER_DEFINED_TRIGGERS

#define NUMBER_DEFINED_AND_MIN 0
#define NUMBER_DEFINED_AND_MAX NUMBER_DEFINED_AND

#define NUMBER_DEFINED_OR_MIN 0
#define NUMBER_DEFINED_OR_MAX NUMBER_DEFINED_OR

#define NUMBER_DEFINED_XOR_MIN 0
#define NUMBER_DEFINED_XOR_MAX NUMBER_DEFINED_XOR

#define NUMBER_DEFINED_NOT_MIN 0
#define NUMBER_DEFINED_NOT_MAX NUMBER_DEFINED_NOT

#define TIMEOUT_DF_PAUSE_MIN 0
#define TIMEOUT_DF_PAUSE_MAX 600000

#define TIMEOUT_DF_WORK_MIN 0
#define TIMEOUT_DF_WORK_MAX 600000

#define TIMEOUT_DR_ELONGATION_MIN 0
#define TIMEOUT_DR_ELONGATION_MAX 600000

#define TIMEOUT_PREFAULT_MIN 100
#define TIMEOUT_PREFAULT_MAX 5000

#define TIMEOUT_POSTFAULT_MIN 100
#define TIMEOUT_POSTFAULT_MAX 15000

#define NUMBER_LINES_FORWARD_MIN 1
#define NUMBER_LINES_BACKWARD_MIN 0
#define NUMBER_LINES_MAX 8

#define SETPOINT_DOVGYNA_VMP_MIN 1
#define SETPOINT_DOVGYNA_VMP_MAX 40000

#define SETPOINT_OPIR_VMP_MIN 1
#define SETPOINT_OPIR_VMP_MAX 20000

#endif
