#ifndef __CONST_MENU_ZSCH__
#define __CONST_MENU_ZSCH__

#define EKRAN_CONTROL_SZKh (EKRAN_CONTROL_RPN + 1)

enum _index_ml_ctrl_szkh
{
  INDEX_ML_CTRZSKh_STATE = 0,

  MAX_ROW_FOR_CONTROL_SZKh

};

#define CTR_MTZ04_MASKA (MASKA_FOR_BIT(MAX_ROW_FOR_CONTROL_SZKh) - 1)

#endif
