#ifndef __CONST_MENU_ZNKh__
#define __CONST_MENU_ZNKh__

#define EKRAN_TIMEOUT_ZNKh_GROUP1 (EKRAN_CONTROL_ZNAM + 1)
#define EKRAN_TIMEOUT_ZNKh_GROUP2 (EKRAN_TIMEOUT_ZNKh_GROUP1 + 1)
#define EKRAN_TIMEOUT_ZNKh_GROUP3 (EKRAN_TIMEOUT_ZNKh_GROUP2 + 1)
#define EKRAN_TIMEOUT_ZNKh_GROUP4 (EKRAN_TIMEOUT_ZNKh_GROUP3 + 1)
#define EKRAN_CONTROL_ZNKh (EKRAN_TIMEOUT_ZNKh_GROUP4 + 1)

enum _index_ml_tmo_znkh
{
  INDEX_ML_TMOZNKh_PEREKL = 0,

  MAX_ROW_FOR_TIMEOUT_ZNKh
};

#define COL_TMO_ZNKh_PEREKL_BEGIN 4
#define COL_TMO_ZNKh_PEREKL_COMMA 6
#define COL_TMO_ZNKh_PEREKL_END 8

enum _index_ml_ctrl_znkh
{
  INDEX_ML_CTRZNKh_STATE = 0,

  MAX_ROW_FOR_CONTROL_ZNKh
};

#define CTR_ZNKh_MASKA (MASKA_FOR_BIT(MAX_ROW_FOR_CONTROL_ZNKh) - 1)

#endif
