#ifndef __CONST_MENU_MEASURMENT__
#define __CONST_MENU_MEASURMENT__

#define EKRAN_MEASURMENT (EKRAN_COFIGURATION + 1)
#define EKRAN_MEASURMENT_1 (EKRAN_MEASURMENT + 1)
#define EKRAN_MEASURMENT_2 (EKRAN_MEASURMENT_1 + 1)
#define EKRAN_MEASURMENT_SELSYN (EKRAN_MEASURMENT_2 + 1)
#define EKRAN_VOLTAGE_SELSYN (EKRAN_MEASURMENT_SELSYN + 1)
#define EKRAN_ANGLE_SELSYN (EKRAN_VOLTAGE_SELSYN + 1)
#define EKRAN_LOGOMETR (EKRAN_ANGLE_SELSYN + 1)
#define EKRAN_MEASURMENT_FREQUENCY (EKRAN_LOGOMETR + 1)

enum
{
  INDEX_ML_MEASURMENT_1 = 0,
  INDEX_ML_MEASURMENT_2,
  INDEX_ML_MEASURMENT_LOGOMETR,
  INDEX_ML_MEASURMENT_SELSYN,
  INDEX_ML_MEASURMENT_FREQUENCY,

  MAX_ROW_FOR_MEASURMENT
};

enum
{
  INDEX_ML_I = 0,
  INDEX_ML_U,

  MAX_ROW_FOR_MEASURMENT_1_AND_2

};

enum
{
  INDEX_ML_MEASURMENT_VOLTAGE = 0,
  INDEX_ML_MEASURMENT_ANGLE,

  MAX_ROW_FOR_MEASURMENT_FOR_SELSYN
};

enum
{
  INDEX_ML_UC1C2 = 0,
  INDEX_ML_UP1P2,
  INDEX_ML_UP2P3,

  MAX_ROW_FOR_MEASURMENT_VOLTAGE_SELSYN
};

enum
{
  INDEX_ML_ANGLE1 = 0,
  INDEX_ML_ANGLE2,

  MAX_ROW_FOR_MEASURMENT_ANGLE_SELSYN

};

enum
{
  INDEX_ML_U_LOGOMETR = 0,
  INDEX_ML_U_LOGOMETR_VYKhID,

  MAX_ROW_FOR_VOLTAGE_LOGOMETR
};

enum
{
  INDEX_ML_F_val_1 = 0,

  MAX_ROW_FOR_MEASURMENT_FREQUENCY

};

#endif
