#ifndef __CONST_MENU_UMAX__
#define __CONST_MENU_UMAX__

#define EKRAN_SETPOINT_UMAX_GROUP1 (EKRAN_SETPOINT_UMIN_GROUP4 + 1)
#define EKRAN_SETPOINT_UMAX_GROUP2 (EKRAN_SETPOINT_UMAX_GROUP1 + 1)
#define EKRAN_SETPOINT_UMAX_GROUP3 (EKRAN_SETPOINT_UMAX_GROUP2 + 1)
#define EKRAN_SETPOINT_UMAX_GROUP4 (EKRAN_SETPOINT_UMAX_GROUP3 + 1)
#define EKRAN_TIMEOUT_UMAX_GROUP1 (EKRAN_TIMEOUT_UMIN_GROUP4 + 1)
#define EKRAN_TIMEOUT_UMAX_GROUP2 (EKRAN_TIMEOUT_UMAX_GROUP1 + 1)
#define EKRAN_TIMEOUT_UMAX_GROUP3 (EKRAN_TIMEOUT_UMAX_GROUP2 + 1)
#define EKRAN_TIMEOUT_UMAX_GROUP4 (EKRAN_TIMEOUT_UMAX_GROUP3 + 1)
#define EKRAN_CONTROL_UMAX (EKRAN_CONTROL_UMIN + 1)

enum _index_ml_stp_Umax
{
  INDEX_ML_STPUmax_Umax1 = 0,
  INDEX_ML_STPUmax_Umax2,

  MAX_ROW_FOR_SETPOINT_Umax
};

#define COL_SETPOINT_Umax_Umax1_BEGIN 5
#define COL_SETPOINT_Umax_Umax1_END 7

#define COL_SETPOINT_Umax_Umax2_BEGIN 5
#define COL_SETPOINT_Umax_Umax2_END 7

enum _index_ml_tmo_Umax
{
  INDEX_ML_TMOUmax_Umax2 = 0,

  MAX_ROW_FOR_TIMEOUT_UMAX
};

#define COL_TMO_Umax_Umax2_BEGIN 5
#define COL_TMO_Umax_Umax2_COMMA 7
#define COL_TMO_Umax_Umax2_END 8

enum _index_ml_ctrl_Umax
{
  INDEX_ML_CTRUmax_STAGE_1 = 0,
  INDEX_ML_CTRUmax_STAGE_2,

  MAX_ROW_FOR_CONTROL_UMAX
};

#define CTR_UMAX_MASKA (MASKA_FOR_BIT(MAX_ROW_FOR_CONTROL_UMAX) - 1)

#endif
