#ifndef __CONST_MENU_RPN__
#define __CONST_MENU_RPN__

#define EKRAN_SETPOINT_RPN_GROUP1 (EKRAN_CHOSE_SETTINGS + 1)
#define EKRAN_SETPOINT_RPN_GROUP2 (EKRAN_SETPOINT_RPN_GROUP1 + 1)
#define EKRAN_SETPOINT_RPN_GROUP3 (EKRAN_SETPOINT_RPN_GROUP2 + 1)
#define EKRAN_SETPOINT_RPN_GROUP4 (EKRAN_SETPOINT_RPN_GROUP3 + 1)
#define EKRAN_TIMEOUT_RPN_GROUP1 (EKRAN_SETPOINT_UP_GROUP4 + 1)
#define EKRAN_TIMEOUT_RPN_GROUP2 (EKRAN_TIMEOUT_RPN_GROUP1 + 1)
#define EKRAN_TIMEOUT_RPN_GROUP3 (EKRAN_TIMEOUT_RPN_GROUP2 + 1)
#define EKRAN_TIMEOUT_RPN_GROUP4 (EKRAN_TIMEOUT_RPN_GROUP3 + 1)
#define EKRAN_CONTROL_RPN (EKRAN_TIMEOUT_UP_GROUP4 + 1)

enum _index_ml_stp_rpn
{
  INDEX_ML_STPRPN_OSN = 0,
  INDEX_ML_STPRPN_ZONE,
  INDEX_ML_STPRPN_MAX_PER,
  INDEX_ML_STPRPN_DOD,
  INDEX_ML_STPRPN_K,

  MAX_ROW_FOR_SETPOINT_RPN
};

#define COL_SETPOINT_RPN_OSN_BEGIN 4
#define COL_SETPOINT_RPN_OSN_COMMA 7
#define COL_SETPOINT_RPN_OSN_END 8

#define COL_SETPOINT_RPN_ZONE_BEGIN 5
#define COL_SETPOINT_RPN_ZONE_COMMA 6
#define COL_SETPOINT_RPN_ZONE_END 7

#define COL_SETPOINT_RPN_MAX_PER_BEGIN 7
#define COL_SETPOINT_RPN_MAX_PER_END 8

#define COL_SETPOINT_RPN_DOD_BEGIN 4
#define COL_SETPOINT_RPN_DOD_COMMA 7
#define COL_SETPOINT_RPN_DOD_END 8

#define COL_SETPOINT_RPN_K_BEGIN 6
#define COL_SETPOINT_RPN_K_COMMA 7
#define COL_SETPOINT_RPN_K_END 9

enum _index_ml_tmo_rpn
{
  INDEX_ML_TMORPN_UB_PRYB = 0,
  INDEX_ML_TMORPN_UB_PRYB_PRYSK,
  INDEX_ML_TMORPN_PRYSK_VID_UMAX,
  INDEX_ML_TMORPN_PEREKL,
  INDEX_ML_TMORPN_NESPR,

  MAX_ROW_FOR_TIMEOUT_RPN
};

#define COL_TMO_RPN_UB_PRYB_BEGIN 5
#define COL_TMO_RPN_UB_PRYB_END 7

#define COL_TMO_RPN_UB_PRYB_PRYSK_BEGIN 5
#define COL_TMO_RPN_UB_PRYB_PRYSK_END 7

#define COL_TMO_RPN_PRYSK_VID_UMAX_BEGIN 5
#define COL_TMO_RPN_PRYSK_VID_UMAX_COMMA 7
#define COL_TMO_RPN_PRYSK_VID_UMAX_END 8

#define COL_TMO_RPN_PEREKL_BEGIN 4
#define COL_TMO_RPN_PEREKL_COMMA 6
#define COL_TMO_RPN_PEREKL_END 8

#define COL_TMO_RPN_NESPR_BEGIN 4
#define COL_TMO_RPN_NESPR_COMMA 6
#define COL_TMO_RPN_NESPR_END 8

enum _index_ml_ctrl_rpn
{
  INDEX_ML_CTRRPN_TRANSF = 0,
  INDEX_ML_CTRRPN_REGYM,
  INDEX_ML_CTRRPN_TM_MODE,
  INDEX_ML_CTRRPN_DOD_KONTUR,
  INDEX_ML_CTRRPN_STRUMOVA_COMP,

  INDEX_ML_CTRRPN_STATE,
  INDEX_ML_CTRRPN_2_GRUPA_USTAVOK,
  INDEX_ML_CTRRPN_OSNOVNYJ_TN2,
  INDEX_ML_CTRRPN_PERMIT_TEST,

  MAX_ROW_FOR_CONTROL_RPN

};
#define CTR_RPN_MASKA (MASKA_FOR_BIT(MAX_ROW_FOR_CONTROL_RPN) - 1)

#endif
