#ifndef __CONST_KOEF_POVERNEBBJA__
#define __CONST_KOEF_POVERNEBBJA__

#define V_1_15_U_nom 115000
#define V_0_80_U_nom 80000

#define KOEF_POVERNENNJA_U_DOWN 999
#define KOEF_POVERNENNJA_U_UP 1001
#define DILNYK_KOEF_POVERNENNJA_U 1000

#define KOEF_POVERNENNJA_U_DOWN_MAX_MIN 99
#define KOEF_POVERNENNJA_U_UP_MAX_MIN 101
#define DILNYK_KOEF_POVERNENNJA_U_MAX_MIN 100

#define KOEF_POVERNENNJA_I 95
#define DILNYK_KOEF_POVERNENNJA_I 100

#define PORIG_CHUTLYVOSTI_DETECTORA_KUTA 6000

#endif
